2024-04-20 20:59:46,893 fflow.py init [line:691] INFO PROCESS ID:	9244
2024-04-20 20:59:46,893 fflow.py init [line:692] INFO Initializing devices: cuda:0 will be used for this running.
2024-04-20 20:59:46,893 fflow.py init [line:695] INFO BENCHMARK:	svhn_classification
2024-04-20 20:59:46,894 fflow.py init [line:696] INFO TASK:			./svhn_DP_Laplace
2024-04-20 20:59:46,894 fflow.py init [line:697] INFO MODEL:		svhn_classification.model.default_model
2024-04-20 20:59:46,896 fflow.py init [line:698] INFO ALGORITHM:	PPFL_DP
2024-04-20 20:59:46,912 fflow.py init [line:737] INFO SCENE:		horizontal FL with 1 <class 'DP.Server'>, 100 <class 'DP.Client'>
2024-04-20 20:59:47,049 fflow.py init [line:754] INFO SIMULATOR:	<class 'flgo.simulator.default_simulator.Simulator'>
2024-04-20 20:59:47,050 fflow.py init [line:767] INFO Ready to start.
2024-04-20 20:59:47,214 fedbase.py _load_checkpoint [line:713] INFO Failed to load checkpoint due to [WinError 3] 系统找不到指定的路径。: './svhn_DP_Laplace\\checkpoint\\1'
2024-04-20 20:59:47,215 fedbase.py run [line:242] INFO --------------Initial Evaluation--------------
2024-04-20 20:59:47,215 simple_logger.py log_once [line:14] INFO Current_time:0
